ALTER TABLE SSO_AD_USERS 
    ADD CONSTRAINT SSO_AD_USERS_PK PRIMARY KEY ( ID ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_APPLICATION 
    ADD CONSTRAINT SSO_APPLICATION_PK PRIMARY KEY ( ID ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_COMPANY_ROLE 
    ADD CONSTRAINT SSO_COMPANY_ROLE_PK PRIMARY KEY ( ID ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_DEALERS 
    ADD CONSTRAINT SSO_DEALERS_PK PRIMARY KEY ( ID ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_GEO_AREAS 
    ADD CONSTRAINT SSO_GEO_AREAS_PK PRIMARY KEY ( ID ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_GEO_COUNTRIES 
    ADD CONSTRAINT SSO_GEO_COUNTRIES_PK PRIMARY KEY ( ID ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_GEO_REGIONS 
    ADD CONSTRAINT SSO_GEO_REGIONS_PK PRIMARY KEY ( ID ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_ROLE 
    ADD CONSTRAINT SSO_ROLE_PK PRIMARY KEY ( ID ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_USER_AREA 
    ADD CONSTRAINT SSO_USER_AREA_PK PRIMARY KEY ( ID_GEO_AREAS, ID_USER ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_USER_COUNTRIES 
    ADD CONSTRAINT SSO_USER_COUNTRIES_PK PRIMARY KEY ( ID_GEO_COUNTRIES, ID_USER ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_USER_DEALERS 
    ADD CONSTRAINT SSO_USER_DEALERS_PK PRIMARY KEY ( ID_DEALERS, ID_USER ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;

ALTER TABLE SSO_USER_REGIONS 
    ADD CONSTRAINT SSO_USER_REGIONS_PK PRIMARY KEY ( ID_GEO_REGIONS, ID_USER ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;


ALTER TABLE SSO_USER_ROLE 
    ADD CONSTRAINT SSO_USER_ROLE_PK PRIMARY KEY ( ID_ROLE, ID_USER ) 
    USING INDEX 
        PCTFREE 10 
        INITRANS 2 
        MAXTRANS 255 
        TABLESPACE USERS 
        LOGGING 
        STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
    ) ;




ALTER TABLE SSO_GEO_COUNTRIES 
    ADD CONSTRAINT FK_SSO_GEO_COUNTRIES_ID_REGION FOREIGN KEY 
    ( 
     ID_REGION
    ) 
    REFERENCES SSO_GEO_REGIONS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_GEO_REGIONS 
    ADD CONSTRAINT FK_SSO_GEO_REGIONS_ID_AREA FOREIGN KEY 
    ( 
     ID_AREA
    ) 
    REFERENCES SSO_GEO_AREAS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_ROLE 
    ADD CONSTRAINT FK_SSO_ROLE_APPLICATION_ID FOREIGN KEY 
    ( 
     APPLICATION_ID
    ) 
    REFERENCES SSO_APPLICATION 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_AREA 
    ADD CONSTRAINT FK_SSO_USER_AREA_ID_GEO_AREAS FOREIGN KEY 
    ( 
     ID_GEO_AREAS
    ) 
    REFERENCES SSO_GEO_AREAS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_AREA 
    ADD CONSTRAINT FK_SSO_USER_AREA_ID_USER FOREIGN KEY 
    ( 
     ID_USER
    ) 
    REFERENCES SSO_AD_USERS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_COUNTRIES 
    ADD CONSTRAINT FK_SSO_USER_COUNTRIES_ID_USER FOREIGN KEY 
    ( 
     ID_USER
    ) 
    REFERENCES SSO_AD_USERS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_DEALERS 
    ADD CONSTRAINT FK_SSO_USER_DEALERS_ID_DEALERS FOREIGN KEY 
    ( 
     ID_DEALERS
    ) 
    REFERENCES SSO_DEALERS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_DEALERS 
    ADD CONSTRAINT FK_SSO_USER_DEALERS_ID_USER FOREIGN KEY 
    ( 
     ID_USER
    ) 
    REFERENCES SSO_AD_USERS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_REGIONS 
    ADD CONSTRAINT FK_SSO_USER_REGIONS_ID_USER FOREIGN KEY 
    ( 
     ID_USER
    ) 
    REFERENCES SSO_AD_USERS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_ROLE 
    ADD CONSTRAINT FK_SSO_USER_ROLE_ID_ROLE FOREIGN KEY 
    ( 
     ID_ROLE
    ) 
    REFERENCES SSO_ROLE 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_ROLE 
    ADD CONSTRAINT FK_SSO_USER_ROLE_ID_USER FOREIGN KEY 
    ( 
     ID_USER
    ) 
    REFERENCES SSO_AD_USERS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_COUNTRIES 
    ADD CONSTRAINT SSOUSERCOUNTRIESIDGEOCOUNTRIES FOREIGN KEY 
    ( 
     ID_GEO_COUNTRIES
    ) 
    REFERENCES SSO_GEO_COUNTRIES 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SSO_USER_REGIONS 
    ADD CONSTRAINT SSO_USER_REGIONSID_GEO_REGIONS FOREIGN KEY 
    ( 
     ID_GEO_REGIONS
    ) 
    REFERENCES SSO_GEO_REGIONS 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;