CREATE TABLE SSO_AD_USERS 
    ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     COMPANY VARCHAR2 (255 BYTE) , 
     COST_CENTER VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_LAST_UPDATE TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     EMAIL VARCHAR2 (255 BYTE) , 
     FAX VARCHAR2 (255 BYTE) , 
     FE_GROUP VARCHAR2 (255 BYTE) , 
     FE_ROLE VARCHAR2 (255 BYTE) , 
     FIRST_NAME VARCHAR2 (255 BYTE) , 
     LANGUAGE VARCHAR2 (255 BYTE) , 
     LAST_NAME VARCHAR2 (255 BYTE) , 
     PASSWORD VARCHAR2 (255 BYTE) , 
     PHONE VARCHAR2 (255 BYTE) , 
     SOURCE VARCHAR2 (255 BYTE) , 
     STATUS VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     USERNAME VARCHAR2 (255 BYTE) 
    )
;

CREATE TABLE SSO_APPLICATION 
    ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     NAME VARCHAR2 (255 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) 
    )
;

CREATE TABLE SSO_COMPANY_ROLE 
    ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     NAME VARCHAR2 (255 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) 
    )
;

CREATE TABLE SSO_DEALERS 
    ( 
     ID VARCHAR2 (255 BYTE)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     ADDRESS VARCHAR2 (255 BYTE) , 
     CITY VARCHAR2 (255 BYTE) , 
     COMPLEMENT VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DEALER_TYPE VARCHAR2 (255 BYTE) , 
     EMAIL VARCHAR2 (255 BYTE) , 
     FAX VARCHAR2 (255 BYTE) , 
     FLAG_AFTERMARKET VARCHAR2 (255 BYTE) , 
     FLAG_ALLUMINIUM VARCHAR2 (255 BYTE) , 
     FLAG_ASSISTANCE VARCHAR2 (255 BYTE) , 
     FLAG_BODYSHOP VARCHAR2 (255 BYTE) , 
     FLAG_DEALER VARCHAR2 (255 BYTE) , 
     FLAG_DEALERSELECTION VARCHAR2 (255 BYTE) , 
     FLAG_EUROPEASS VARCHAR2 (255 BYTE) , 
     FLAG_FLAGSHIP VARCHAR2 (255 BYTE) , 
     FLAG_HVR VARCHAR2 (255 BYTE) , 
     FLAG_IMPORTER VARCHAR2 (255 BYTE) , 
     FLAG_PDICENTER VARCHAR2 (255 BYTE) , 
     FLAG_POS VARCHAR2 (255 BYTE) , 
     FLAG_REGIONALOFFICE VARCHAR2 (255 BYTE) , 
     FLAG_REGIONALOFFICE_SUBSIDIARY VARCHAR2 (255 BYTE) , 
     FLAG_SHOWROOM VARCHAR2 (255 BYTE) , 
     FLAG_SUBDEALER VARCHAR2 (255 BYTE) , 
     FLAG_SUBSIDIARY VARCHAR2 (255 BYTE) , 
     GL_LATITUDE NUMBER (38) , 
     GL_LONGITUDE NUMBER (38) , 
     HOUSE_NUMBER VARCHAR2 (255 BYTE) , 
     NAME VARCHAR2 (255 BYTE) , 
     PHONE VARCHAR2 (255 BYTE) , 
     PROVINCE VARCHAR2 (255 BYTE) , 
     PROVINCE_CODE VARCHAR2 (255 BYTE) , 
     SW_ENABLED VARCHAR2 (255 BYTE) , 
     SW_HEADING NUMBER (38) , 
     SW_LATITUDE NUMBER (38) , 
     SW_LONGITUDE NUMBER (38) , 
     SW_PITCH NUMBER (38) , 
     SW_ZOOM NUMBER (38) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     VILLAGE VARCHAR2 (255 BYTE) , 
     WEBSITE VARCHAR2 (255 BYTE) , 
     ZIPCODE VARCHAR2 (255 BYTE) , 
     COUNTRY_CODE VARCHAR2 (255 BYTE) 
    )
;

CREATE TABLE SSO_GEO_AREAS 
    ( 
     ID VARCHAR2 (255 BYTE)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DESCRIPTION_DE VARCHAR2 (255 BYTE) , 
     DESCRIPTION_EN VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ES VARCHAR2 (255 BYTE) , 
     DESCRIPTION_FR VARCHAR2 (255 BYTE) , 
     DESCRIPTION_IT VARCHAR2 (255 BYTE) , 
     DESCRIPTION_JP VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ZH VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) 
    )
;

CREATE TABLE SSO_GEO_COUNTRIES 
    ( 
     ID VARCHAR2 (255 BYTE)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DESCRIPTION_DE VARCHAR2 (255 BYTE) , 
     DESCRIPTION_EN VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ES VARCHAR2 (255 BYTE) , 
     DESCRIPTION_FR VARCHAR2 (255 BYTE) , 
     DESCRIPTION_IT VARCHAR2 (255 BYTE) , 
     DESCRIPTION_JP VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ZH VARCHAR2 (255 BYTE) , 
     ID_ISO3166 VARCHAR2 (255 BYTE) , 
     ID_ISO3166_3 VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     ID_REGION VARCHAR2 (255 BYTE) 
    )
;

CREATE TABLE SSO_GEO_REGIONS 
    ( 
     ID VARCHAR2 (255 BYTE)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DESCRIPTION_DE VARCHAR2 (255 BYTE) , 
     DESCRIPTION_EN VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ES VARCHAR2 (255 BYTE) , 
     DESCRIPTION_FR VARCHAR2 (255 BYTE) , 
     DESCRIPTION_IT VARCHAR2 (255 BYTE) , 
     DESCRIPTION_JP VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ZH VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     ID_AREA VARCHAR2 (255 BYTE) 
    ) 
;

CREATE TABLE SSO_ROLE 
    ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     NAME VARCHAR2 (255 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) , 
     APPLICATION_ID NUMBER (19) 
    )
;

CREATE TABLE SSO_USER_AREA 
    ( 
     ID_GEO_AREAS VARCHAR2 (255 BYTE)  NOT NULL , 
     ID_USER NUMBER (19)  NOT NULL 
    ) 
;

CREATE TABLE SSO_USER_COUNTRIES 
    ( 
     ID_GEO_COUNTRIES VARCHAR2 (255 BYTE)  NOT NULL , 
     ID_USER NUMBER (19)  NOT NULL 
    ) 
;

CREATE TABLE SSO_USER_DEALERS 
    ( 
     ID_DEALERS VARCHAR2 (255 BYTE)  NOT NULL , 
     ID_USER NUMBER (19)  NOT NULL 
    ) 
;

CREATE TABLE SSO_USER_REGIONS 
    ( 
     ID_GEO_REGIONS VARCHAR2 (255 BYTE)  NOT NULL , 
     ID_USER NUMBER (19)  NOT NULL 
    ) 
;

CREATE TABLE SSO_USER_ROLE 
    ( 
     ID_ROLE NUMBER (19)  NOT NULL , 
     ID_USER NUMBER (19)  NOT NULL 
    ) 
;